name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: yarn install && yarn workspace @training-calculator/website install:e2e
      - name: Lint
        run: yarn workspace @training-calculator/website lint
      - name: Test
        run: yarn workspace @training-calculator/website test
      - name: Build
        run: yarn workspace @training-calculator/website build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./packages/website/out/
